config/routes.rb
Pereiraefranco::Application.routes.draw do
  
  resources :event_photos, :only=>[:before_image,:after_image] do
    get :before_image, :on => :member
    get :after_image, :on => :member
  end
  
  resources :events, :only => [:cover_image,:index,:show] do
    get :cover_image, :on => :member
  end
  
  
  resources :email_message, :only => [:index,:new, :create] 
  
  scope '/admin' do
    devise_for :admin
  end
  
  namespace "admin" do
    resources :events do
      resources :event_photos, :only => [:create,:destroy]
    end
  end
  

  root :to => 'pages#index'
  
  get 'pages/about_us'
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_photos
  attr_accessible :description, :event_date, :name,
  :cover_file_name, :cover_content_type, :cover_binary_data, :cover_image_file,
  :event_photos
  
  validates_presence_of :event_date, :name, :cover_image_file

  def cover_image_file=(input_data)
    self.cover_file_name = input_data.original_filename
    self.cover_content_type = input_data.content_type.chomp
    self.cover_binary_data = input_data.read
  end
  
  def cover_image_file
    return_data = nil
    unless (self.cover_file_name.nil?)
      return_data = ActionDispatch::Http::UploadedFile.new({
        :filename => self.cover_file_name,
        :content_type => self.cover_content_type,
        :tempfile => self.cover_binary_data
      })
    end
    return_data
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController

  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @event = Event.new
    respond_with @event
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params[:event])

    respond_with do |format|
      if @event.save
        format.html { redirect_to admin_events_url, notice: 'Event was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @event = Event.find(params[:id])

    respond_with do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to admin_events_url, notice: 'Event was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_with do |format|
      format.html { redirect_to admin_events_url }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def cover_image
    @event = Event.find(params[:id])
    @image = @event.cover_binary_data
    send_data(@image,  :type     => @event.cover_content_type, 
                       :filename => @event.cover_file_name, 
                       :disposition => 'inline')
  end
  
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    respond_with @events do |format|
      format.html
      format.js
    end
    
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    respond_with(@event)
  
    #render event_path(@event)
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<%= form_for([:admin,@event], :multipart => true) do |f| %>
<% if @event.errors.any? %>
<div id="error_explanation">
	<ul>
		<% @event.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row">
	<div class="large-12 columns">
		<%= 
		unless @event.cover_file_name.nil?
			image_tag(cover_image_event_path(@event))	
		else
			image_tag("image_not_set.png")
		end
		 %>
	</div>
</div>
<div class="row">
	<div class="large-6 large-centered columns">
		<%= f.label :cover_image_file %>
		<br />
		<%= f.file_field :cover_image_file %>
	</div>
</div>
<div class="row">
	<div class="large-4 columns">
		<%= f.text_field :name, :placeholder => "Evento" %>
	</div>
	<div class="large-4 columns">
		<%= f.text_field :description, :placeholder => "Descrição" %>
	</div>
	<div class="large-4 columns">
		<%= f.text_field :event_date, :data => {:field_type => "date"}, :placeholder => "Data" %>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<ul class="large-block-grid-5 clearing-thumbs" data-clearing>
			<% @event.event_photos.each do |ep| %>
			<li>
				<div class="row">
					<div class="large-6 columns">
						<%= link_to(before_image_event_photo_url(ep) ) do %>
						<%= image_tag(before_image_event_photo_url(ep),
						:alt => ep.before_file_name) %>
						<% end %>
					</div>
					<div class="large-6 columns">
						<%= link_to(after_image_event_photo_url(ep) ) do %>
						<%= image_tag(after_image_event_photo_url(ep),
						:alt => ep.after_file_name) %>
						<% end %>
					</div>
				</div>
				<div class="row">
					<%= link_to 'Excluir', admin_event_event_photo_path(@event,ep),
					method: :delete, data: { confirm: 'Você tem certeza?' },
					:class => "button expand" %>
					<div class="large-12 columns"></div>
				</div>
			</li>
			<% end %>
		</ul>
	</div>
</div>

<div class="actions">
	<%= f.submit :class => "button" %>
</div>
<% end %>
<% @event_photo = EventPhoto.new %>

app/views/admin/events/edit.html.erb
<h1><%= t(".title") %></h1>

<%= render "form" %>
<%= render "admin/event_photos/form", :event => @event, :event_photo => @event_photo %>

<%= link_to t("back").humanize, admin_events_path, :class => "button" %>

app/views/admin/events/index.html.erb
<h1><%= t(".title") %></h1>
<ul class="small-block-grid-1 large-block-grid-4">
	<% @events.each do |event| %>
	<li>
		<%= link_to edit_admin_event_path(event) do %>
		<div class="row">
			<div>
				<span><%= event.name %></span>
			</div>
			<div class="large-12 columns">
				<%= unless event.cover_file_name.nil? then
          image_tag(cover_image_event_url(event),
				:alt => 'image', 'data-caption' => 'CAPTION')
        end %>
			</div>
			<div>
				<%= l event.event_date %>
			</div>
		</div>
		<% end %>

		<div class="row">
			<div class="large-12 columns">
				<%= link_to 'Deletar', admin_event_path(event), method: :delete, data: { confirm: 'Are you sure?' },
					:class => "button" %>
			</div>
		</div>
	</li>
	<% end %>
</ul>
<br />

<%= link_to 'Novo', new_admin_event_path, :class => "button" %>

app/views/admin/events/new.html.erb
<h1><%= t(".title") %></h1>

<%= render 'form' %>

<%= link_to t("back").humanize, admin_events_path, :class => "button" %>

app/views/admin/events/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>
	<b>Name:</b>
	<%= @event.name %>
</p>

<p>
	<b>Description:</b>
	<%= @event.description %>
</p>

<p>
	<b>Event date:</b>
	<%= l @event.event_date %>
</p>

<div class="row">
	<div class="large-12 columns">
		<ul class="small-block-grid-1 large-block-grid-5 clearing-thumbs" data-clearing>
			<% @event.event_photos.each do |ep| %>
			<li>
				<%= link_to(image_event_photo_url(ep) ) do %>
				<%= image_tag(image_event_photo_url(ep),
				:alt => 'image', 'data-caption' => 'CAPTION') %>
				<% end %>
			</li>
			<% end %>
		</ul>
	</div>
</div>

<%= link_to t("edit").humanize, edit_admin_event_path(@event) %> |
<%= link_to t("back").humanize, events_path %>