config/routes.rb
Pereiraefranco::Application.routes.draw do
  
  resources :event_photos, :only=>[:before_image,:after_image] do
    get :before_image, :on => :member
    get :after_image, :on => :member
  end
  
  resources :events, :only => [:cover_image,:index,:show] do
    get :cover_image, :on => :member
  end
  
  
  resources :email_message, :only => [:index,:new, :create] 
  
  scope '/admin' do
    devise_for :admin
  end
  
  namespace "admin" do
    resources :events do
      resources :event_photos, :only => [:create,:destroy]
    end
  end
  

  root :to => 'pages#index'
  
  get 'pages/about_us'
  

end

app/models/email_message.rb
class EmailMessage < ActiveRecord::Base
  attr_accessible :body, :from, :name, :subject
  
  validates_format_of :from, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_presence_of :name, :from, :body

  after_create :send_email

protected

  def send_email
    ContactMailer.contact_message(self).deliver
  end

  
end

app/controllers/email_message_controller.rb
class EmailMessageController < ApplicationController
  
  def new
    @email_message = EmailMessage.new
  end

  def create
    @email_message = EmailMessage.new(params[:email_message])

    if @email_message.save
      flash[:notice] = 'Sua mensagem foi enviada.'
      redirect_to new_email_message_path
    else
      render :new
    end
  end

  
end

app/views/email_message/new.html.erb
<div class="row">
	<% if @email_message.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@email_message.errors.count, "error") %> prohibited this event from being saved:</h2>

		<ul>
			<% @email_message.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
			<% end %>
		</ul>
	</div>
	<% end %>
</div>
<div class="row">
	
	<%= form_for @email_message, url: email_message_index_path do |f| %>

	<div class="field">
		<%= f.text_field :subject, :placeholder => "Assunto" %>
	</div>

	<div class="field">
		<%= f.text_field :name, :placeholder => "Nome" %>
	</div>

	<div class="field">
		<%= f.text_field :from, :placeholder => "Email" %>
	</div>

	<div class="field">
		<%= f.text_area :body, :placeholder => "" %>
	</div>

	<p>
		<%= f.submit  "Enviar", :class => "button" %>
	</p>
	<% end %>
</div>
<div class="row">
	Ou pelo telefone: (015) 3012-2067
</div>