config/routes.rb
Pereiraefranco::Application.routes.draw do
  
  resources :event_photos, :only=>[:before_image,:after_image] do
    get :before_image, :on => :member
    get :after_image, :on => :member
  end
  
  resources :events, :only => [:cover_image,:index,:show] do
    get :cover_image, :on => :member
  end
  
  
  resources :email_message, :only => [:index,:new, :create] 
  
  scope '/admin' do
    devise_for :admin
  end
  
  namespace "admin" do
    resources :events do
      resources :event_photos, :only => [:create,:destroy]
    end
  end
  

  root :to => 'pages#index'
  
  get 'pages/about_us'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
	<!--<![endif]-->
	<head>
		<meta charset="utf-8" />
		<!-- Set the viewport width to device width for mobile -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title><%= content_for?(:title) ? yield(:title) : "Pereira & Franco Cenografias e Eventos" %></title>
		<%= stylesheet_link_tag "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" %>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "vendor/custom.modernizr" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>

	<body>
		<header class="row">
				<div class="small-12 columns">
					<h1 class="logo">
						<%= link_to(root_url) do %>
						<div class="row">
						<div class="small-12 columns name">
							PereiraEFranco
						</div>
						</div>
						<div class="row">
						<div class="small-12 columns service">
							<span class="first-letter">C</span>enografias
							<span class="first-letter"> & </span>
							<span class="first-letter">E</span>ventos
						</div>
						</div>
						<% end %>
	
					</h1>
					</div>
		</header>
		<nav class="top-bar">
							<ul class="title-area">
								<li class="name">
								</li>
								<li class="toggle-topbar menu-icon">
									<a href="#"><span>Menu</span></a>
								</li>
							</ul>
							<section class="top-bar-section">
								<ul class="left">
									<li class="divider"></li>
									<%if admin_signed_in? %>
									<li class="has-dropdown">
										<a href="#">Eventos</a>
										<ul class="dropdown">
											<li <%= if current_page?(events_url) then 'class=active' end %> >
												<%= link_to "Eventos-Normal", events_url %>
											</li>
											<li <%= if current_page?(admin_events_url) then 'class=active' end %> >
												<%= link_to "Eventos-Admin", admin_events_url %>
											</li>
										</ul>
									</li>
									<% else %>
									<li <%= if current_page?(events_url) then 'class=active' end %> >
										<%= link_to "Eventos", events_url %>
									</li>
									<%end%>
									<li class="divider"></li>
									<li <%= if current_page?(pages_about_us_url) then 'class=active' end %> >
										<%= link_to "Quem Somos", pages_about_us_url %>
									</li>
									<li class="divider"></li>
									<li <%= if current_page?(new_email_message_url) then 'class=active' end %> >
										<%= link_to "Contato", new_email_message_url %>
									</li>
									<li class="divider"></li>
									<li class="divider"></li>
									<%if admin_signed_in? %>
									<li>
										<%= link_to "Sair", destroy_admin_session_url, :method => :delete %>
									</li>
									<% else %>
									<li <%= if current_page?(admin_session_url) then 'class=active' end %> >
										<%= link_to "Entrar", admin_session_url %>
									</li>
									<%end%>
									<li class="divider"></li>
								</ul>
							</section>
						</nav>
		<div id="main" class="row">
			<div id="page-<%=controller.controller_name + "-" + controller.action_name %>" class="small-12 columns">
				<%= yield %>
			</div>
		</div>
	</body>
</html>